import { Inter } from 'next/font/google';
import Head from 'next/head';
// import Link from 'next/link';
import { Link } from '@chakra-ui/next-js';

const inter = Inter({ subsets: ['latin'] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main>
        <ul>
          <li>
            {/* <Link href='/'>Home</Link> */}
            <Link href='/' color='blue.400' _hover={{ color: 'blue.500' }}>
              Home
            </Link>
          </li>
          <li>
            {/* <Link href='/about'>About Us1</Link> */}
            <Link href='/about' color='blue.400' _hover={{ color: 'blue.500' }}>
              About Us
            </Link>
          </li>
        </ul>
      </main>
    </>
  );
}
